export const TYPES = {
	Application: Symbol.for('Application'),
	LoggerService: Symbol.for('LoggerService'),
	ConfigService: Symbol.for('ConfigService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	MongoService: Symbol.for('MongoService'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	UserRepository: Symbol.for('UserRepository'),
	MinioService: Symbol.for('MinioService'),
	UploadController: Symbol.for('UploadController'),
	UploadRepository: Symbol.for('UploadRepository'),
	UploadService: Symbol.for('UploadService'),
	NewsController: Symbol.for('NewsController'),
	NewsRepository: Symbol.for('NewsRepository'),
	NewsService: Symbol.for('NewsService'),
};
